export default [
  'Clothing',
  'Dining out',
  'Education',
  'Entertainment',
  'Groceries',
  'Healthcare',
  'Rent/Mortgage',
  'Transportation',
  'Utilities (Electricity, Water, Gas)',
  'Insurance',
  'Salary',
  'Freelance',
  'Investments',
  'Rental Income',
  'Business Revenue',
  'Dividends',
  'Royalties',
  'Gifts',
  'Side Jobs',
  'Bonuses',
  'Donations',
]