export const icons = [
  { name: 'bonuses', image: require('@/assets/categories/bonuses.png') },
  { name: 'business', image: require('@/assets/categories/business.png') },
  { name: 'dividends', image: require('@/assets/categories/dividends.png') },
  { name: 'freelance', image: require('@/assets/categories/freelance.png') },
  { name: 'gifts', image: require('@/assets/categories/gifts.png') },
  { name: 'investments', image: require('@/assets/categories/investments.png') },
  { name: 'rental', image: require('@/assets/categories/rental.png') },
  { name: 'royalties', image: require('@/assets/categories/royalties.png') },
  { name: 'salary', image: require('@/assets/categories/salary.png') },
  { name: 'side-jobs', image: require('@/assets/categories/side-jobs.png') },
  { name: 'clothing', image: require('@/assets/categories/clothing.png') },
  { name: 'education', image: require('@/assets/categories/education.png') },
  { name: 'entertainment', image: require('@/assets/categories/entertainment.png') },
  { name: 'dining-out', image: require('@/assets/categories/dining-out.png') },
  { name: 'groceries', image: require('@/assets/categories/groceries.png') },
  { name: 'healthcare', image: require('@/assets/categories/healthcare.png') },
  { name: 'insurance', image: require('@/assets/categories/insurance.png') },
  { name: 'rent', image: require('@/assets/categories/rent.png') },
  { name: 'transportation', image: require('@/assets/categories/transportation.png') },
  { name: 'utilities', image: require('@/assets/categories/utilities.png') },
]

export const walletIcons = [
  { name: 'credit-card', image: require('@/assets/icons/credit-card.png') },
  { name: 'business', image: require('@/assets/wallets/business.png') },
  { name: 'camera', image: require('@/assets/wallets/camera.png') },
  { name: 'camera2', image: require('@/assets/wallets/camera2.png') },
  { name: 'cart', image: require('@/assets/wallets/cart.png') },
  { name: 'chart', image: require('@/assets/wallets/chart.png') },
  { name: 'folder', image: require('@/assets/wallets/folder.png') },
  { name: 'graph', image: require('@/assets/wallets/graph.png') },
  { name: 'health', image: require('@/assets/wallets/health.png') },
  { name: 'key', image: require('@/assets/wallets/key.png') },
  { name: 'phone', image: require('@/assets/wallets/phone.png') },
  { name: 'shopping', image: require('@/assets/wallets/shopping.png') },
  { name: 'star', image: require('@/assets/wallets/star.png') },
  { name: 'ticket-star', image: require('@/assets/wallets/ticket-star.png') },
  { name: 'wallet', image: require('@/assets/wallets/wallet.png') },
  { name: 'wallet2', image: require('@/assets/wallets/wallet2.png') },
]
